version: "3.7"

networks:
  alert-queue:
    driver: "bridge"

services:
  php-apache:
    build:
      dockerfile: docker/Dockerfile
      context: ./..
    ports:
      - 80:80
      - 8080:80
    volumes:
      - ../:/var/www/html
    extra_hosts:
      - "alerts.local:127.0.0.1"
    hostname: alerts.local
    domainname: local
    restart: always
    links:
      - redis
    networks:
      - alert-queue


  redis:
    image: redis:4.0
    container_name: alert_redis
    restart: always
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
    volumes:
      - ./redis/data:/data
    ports:
      - "6382:6379"
    networks:
      - alert-queue


